%% Homework 1

% Using ultrasound, data is obtained concerning the spatial 
% variations in a small area of the intestines where the marble 
% is suspected to be. Unfortunately, the internal fluid movement 
% through the intestines generates highly noisy data.
% Locate and compute the trajectory of the marble. 

clear; close all; clc;

% whos -file Testdata.mat
% returns the name, dimensions, size, and  
% data type of all variables in the MAT-file

load Testdata

L = 15; % spatial domain
n = 64; % Fourier modes, i.e. # of points in spatial range (2^6)

% 1x65 vector, includes upper & lower bounds of spatial range [-15,15]
% what is the purpose of this vector
x2 = linspace(-L,L,n+1); 

x = x2(1:n); % x-coord of each point in the discretized spatial range [-15,15)
y = x;  % y-coord of each point in the discretized spatial range [-15,15)
z = x;  % z-coord of each point in the discretized spatial range [-15,15)

% wavenumbers (eigenvalues)
% 1x64 vector [[0,6.4926], [-6.7021, -0.2094]]
% goes from 0 to highest, then from lowest to 0
% scaling is 2pi/L  (why is code this 2pi/2L?)
k= (2*pi/(2*L))*[0:(n/2-1) -n/2:-1];

% 1x64 vector [-6.7021, 6.4926]
% goes from lowest to highest
ks=fftshift(k);

% grid with spatial coordinates
[X,Y,Z] = meshgrid(x,y,z);
% grid with frequency values
[Kx,Ky,Kz] = meshgrid(ks,ks,ks);

%% 1
% Through averaging of the spectrum, determine the frequency signature 
%(center frequency) generated by the marble.

Un = zeros(n,n,n);
Un_fft = zeros(n,n,n);
mean_fft = zeros(n,n,n); 

for j=1:20  % because we have 20 rows
   % Creates a 3D grid for each observation in Undata
   % this is the value of our function at each 
   % discretized point in space
    Un(:,:,:,j) = reshape(Undata(j,:),n,n,n); % stores the grid data 
  
    % transform the grid data to the frequency domain
    Un__fft(:,:,:,j) = fftn(Un(:,:,:,j));
   
    % uses the function values to transform to signal data
   % cumulative sum of signal values at each point in the grid
    mean_fft = mean_fft + Un__fft(:,:,:,j);
   
    % close all, isosurface(X,Y,Z,abs(Un),0.4)
   % axis([-20 20 -20 20 -20 20]), grid on, drawnow
   % pause(2)
end

% do we need fftshift here?
mean_fft = abs(mean_fft)./20;  

% and this occurs at indexes:
% (0, 9, 59)
% or if I do fftshift the indices are:
% (32, 41, 27)

% vectorizes the matrix and get max value
max_signal = max(mean_fft(:));   %271.8673

% find the indices of the maximum value in the grid
% (60, 10, 1)
[max_x, max_y, max_z] = ind2sub(size(mean_fft), find(mean_fft == max_signal));

% using the max coordinates, find frequencies associated with max signal
% (-3.1416, 5.8643, 3.3510) 
kx_center = Kx(max_x, max_y, max_z);  % -4.8171
ky_center = Ky(max_x, max_y, max_z);  % 5.6549
kz_center = Kz(max_x, max_y, max_z);  % -6.7021

%% 2
% Filter the data around the center frequency determined above in 
% order to denoise the data and determine the path of the marble. 
% (use plot3 to plot the path once you have it)

% Since we have three different frequencies (in x, y, and z direction)
% for each point in the grid, we use the formula
% exp(-0.2*((kx - kx_0).^2 + (ky - ky_0).^2 + (kz - kz_0).^2); 
% where 0.2 is the tau value which is the width of our filter
% has something to do with the Heisenberg Uncertainty Principle?
% I think the wider our filter, the more accurate the 
% signal in the time domain will be

filter = exp(-0.2*((Kx(:,:,:) - kx_center).^2 ... 
    + (Ky(:,:,:) - ky_center).^2 ... 
    + (Kz(:,:,:) - kz_center).^2)); 


% now multiply the fiter value grid and the unfiltered data grid

Un_fft_filtered = zeros(n,n,n);

for j=1:1  % just bumped this down to one to troubleshoot
   Un_fft_filtered(:,:,:,j) = Un__fft(:,:,:,j).*filter
   % plot the signal data in the frequency domain
   close all, isosurface(Kx,Ky,Kz,abs(Un_fft_filtered(:,:,:,j)),0.00005)
   axis([-10 10 -10 10 -10 10]), grid on, drawnow
   pause(5)
end

%% THIS DOESN'T WORK, THE PLOT IS A CUBE
% convert the filtered fft data back to the spatial domain
% plot3(X,Y,Z)

Un_filtered = zeros(n,n,n);

for j=1:1  % just bumped this down to one to troubleshoot
   Un_filtered(:,:,:,j) = ifftn(Un_fft_filtered(:,:,:,j));
   % plot the signal data in the spatial domain
   close all, isosurface(X,Y,Z,abs(Un_filtered(:,:,:,j)),0.02)
   axis([-40 40 -40 40 -40 40]), grid on, drawnow
   pause(5)
end



%% 3
% Where should an intense acoustic wave be focused 
% to breakup the marble at the 20th data measurement?

% when we get back the signal data in the spatial domain, find
% spatial coordinates of the max signal data?
