%% Homework 1

% Using ultrasound, data is obtained concerning the spatial 
% variations in a small area of the intestines where the marble 
% is suspected to be. Unfortunately, the internal fluid movement 
% through the intestines generates highly noisy data.
% Locate and compute the trajectory of the marble. 

clear; close all; clc;

% whos -file Testdata.mat
% returns the name, dimensions, size, and  
% data type of all variables in the MAT-file

data = load ('Testdata.mat');

Undata = data.Undata;


L = 15; % spatial domain
n = 64; % Fourier modes 2^6

x2 = linspace(-L,L,n+1); % 1x65 vector [-15,15]

x = x2(1:n); % 1x64 vector [-15,15)
y = x; 
z = x;

% wavenumbers (eigenvalues)
% 1x64 vector [[0,6.4926], [-6.7021, -0.2094]]
k= (2*pi/(2*L))*[0:(n/2-1) -n/2:-1];

% 1x64 vector [-6.7021, 6.4926]
ks=fftshift(k);

[X,Y,Z] = meshgrid(x,y,z);
[Kx,Ky,Kz] = meshgrid(ks,ks,ks);


for j=1:20
    % Does this make a 3D array of the first row of Undata?
   Un(:,:,:)=reshape(Undata(j,:),n,n,n);
   % http://www.ece.northwestern.edu/local-apps/matlabhelp/techdoc/ref/isosurface.html
   close all, isosurface(X,Y,Z,abs(Un),0.4)
   axis([-20 20 -20 20 -20 20]), grid on, drawnow
   pause(1)
end

%% 1
% Through averaging of the spectrum, determine the frequency signature 
%(center frequency) generated by the marble.


%% 2
% Filter the data around the center frequency determined above in 
% order to denoise the data and determine the path of the marble. 
% (use plot3 to plot the path once you have it)


%% 3
% Where should an intense acoustic wave be focused 
% to breakup the marble at the 20th data measurement?

